//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PikaCore.Resources.Areas.Identity.Views.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Login_pl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Login_pl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PikaCore.Resources.Areas.Identity.Views.Account.Login.pl", typeof(Login_pl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapomniałeś hasła.
        /// </summary>
        internal static string Forgot_your_password {
            get {
                return ResourceManager.GetString("Forgot your password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawne żądanie autoryzacji.
        /// </summary>
        internal static string Incorrect_authorization_request {
            get {
                return ResourceManager.GetString("Incorrect authorization request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj się.
        /// </summary>
        internal static string Log_in {
            get {
                return ResourceManager.GetString("Log in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj się używając konta PikaCloud.
        /// </summary>
        internal static string Log_in_using_PikaCloud_Account {
            get {
                return ResourceManager.GetString("Log in using PikaCloud Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj się używając konta zewnętrznego.
        /// </summary>
        internal static string Log_in_using_third_party_account {
            get {
                return ResourceManager.GetString("Log in using third party account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUB.
        /// </summary>
        internal static string OR {
            get {
                return ResourceManager.GetString("OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestruj się jako nowy użytkownik.
        /// </summary>
        internal static string Register_as_a_new_user {
            get {
                return ResourceManager.GetString("Register as a new user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przepraszamy, ale nie możesz użyć zewnętrznego konta, aby się zalogować..
        /// </summary>
        internal static string Sorry__but_you_can_t_use_any_3rd_party_authorization_provider_at_the_moment {
            get {
                return ResourceManager.GetString("Sorry, but you can\'t use any 3rd party authorization provider at the moment", resourceCulture);
            }
        }
    }
}
