version: '3.9'
services:
  pika-core:
    build: .
    volumes: 
      - /srv/configs/fms/prod/appsettings.json:/app/appsettings.json
    ports:
      - "5000:5000"
    command: ['dotnet', "PikaCore.dll"]
    deploy:
      mode: replicated
      replicas: 2