version: '3.9'
services:
  pika-core:
    build: .
    volumes: 
      - /srv/configs/fms/prod/appsettings.json:/Pika.Core/appsettings.json
      - /srv/fms/certs/prod/:/Pika.Core/certs
      - /srv/fms/wwwroot/lib:/Pika.Core/wwwroot/lib
    ports:
      - "5000"
    expose:
      - "5000"
    command: ['dotnet', "PikaCore.dll"]
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '4.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 500M
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always
    networks:
      - backend
    labels:
      - "traefik.http.routers.pika-core.rule=Host(`core.lukas-bownik.net`)"
      - "traefik.http.routers.pika-core.entrypoints=web2" 
      - "traefik.http.services.pika-core.loadBalancer.sticky.cookie=true"
      - "traefik.http.services.pika-core.loadBalancer.sticky.cookie.name=lbcookie"
      - "traefik.http.services.pika-core.loadBalancer.sticky.cookie.secure=true"
      - "traefik.http.services.pika-core.loadBalancer.sticky.cookie.httponly=true"
      - "traefik.http.services.pika-core.loadBalancer.server.port=5000"
  proxy:
    image: traefik:latest
    command:
      - --providers.docker=true
      - --api=true
      - --entrypoints.web.address=:80
      - --entrypoints.web2.address=:5000
    ports:
      - "5000:5000"
      - "8081:80"
      - "8080:8080"
    labels:
      - "traefik.http.routers.api.rule=Host(`192.168.1.252`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.api.dashboard=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
    
networks:
  backend:
    name: pika-core
    external: true