version: '3.9'
services:
  pika-core:
    build: .
    volumes: 
      - /srv/configs/fms/prod/appsettings.json:/Pika.Core/appsettings.json
      - /srv/fms/certs/prod/:/Pika.Core/certs
      - /srv/fms/wwwroot/lib:/Pika.Core/wwwroot/lib
    ports:
      - "5000:5000"
    command: ['dotnet', "PikaCore.dll"]
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always
networks:
  backend:
    name: pika-core
    external: true
  bridge: