//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PikaCore.Resources.Areas.Core.Controllers.App {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StorageController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StorageController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PikaCore.Resources.Areas.Core.Controllers.App.StorageController", typeof(StorageController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można ukryć zaznaczonego zasobu.
        /// </summary>
        internal static string Couldn_t_be_hidden {
            get {
                return ResourceManager.GetString("Couldn\'t be hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można ukryć tego zasobu.
        /// </summary>
        internal static string Couldn_t_be_set_visible {
            get {
                return ResourceManager.GetString("Couldn\'t be set visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się wygenerować.
        /// </summary>
        internal static string Couldn_t_generate_token_for_that_resource {
            get {
                return ResourceManager.GetString("Couldn\'t generate token for that resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można odczytać rządanego zasobu:.
        /// </summary>
        internal static string Couldn_t_read_requested_resource_ {
            get {
                return ResourceManager.GetString("Couldn\'t read requested resource:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd: Nie można stworzyć katalogu.
        /// </summary>
        internal static string Error__Couldn_t_create_directory {
            get {
                return ResourceManager.GetString("Error: Couldn\'t create directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd: Nie można usunąć zasobu.
        /// </summary>
        internal static string Error__Couldn_t_delete_resource {
            get {
                return ResourceManager.GetString("Error: Couldn\'t delete resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd: Nie zaznaczono nic do usunięcia.
        /// </summary>
        internal static string Error__Nothing_to_be_deleted {
            get {
                return ResourceManager.GetString("Error: Nothing to be deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plik.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik nie istnieje na serwerze.
        /// </summary>
        internal static string File_doesn_t_exist_on_server_s_filesystem {
            get {
                return ResourceManager.GetString("File doesn\'t exist on server\'s filesystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pliki.
        /// </summary>
        internal static string files {
            get {
                return ResourceManager.GetString("files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wygląda na to, że ten token nie istnieje.
        /// </summary>
        internal static string It_seems_that_given_token_doesn_t_exist_in_the_database {
            get {
                return ResourceManager.GetString("It seems that given token doesn\'t exist in the database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wygląda na to, że URL wygasł, wygeneruj nowy.
        /// </summary>
        internal static string It_seems_that_this_url_expired__you_need_to_generate_a_new_one {
            get {
                return ResourceManager.GetString("It seems that this url expired, you need to generate a new one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowa nazwa nie może być pusta.
        /// </summary>
        internal static string New_name_cannot_be_empty {
            get {
                return ResourceManager.GetString("New name cannot be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepodany id albo baza danych nie odpowiada.
        /// </summary>
        internal static string No_id_given_or_database_is_down {
            get {
                return ResourceManager.GetString("No id given or database is down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zasób ukryto.
        /// </summary>
        internal static string Resource_hidden {
            get {
                return ResourceManager.GetString("Resource hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id nie może być puste.
        /// </summary>
        internal static string Resource_id_cannot_be_null {
            get {
                return ResourceManager.GetString("Resource id cannot be null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zasób jest widoczny teraz dla wszystkich.
        /// </summary>
        internal static string Resource_is_visible_now {
            get {
                return ResourceManager.GetString("Resource is visible now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coś poszło nie tak....
        /// </summary>
        internal static string Something_went_wrong___ {
            get {
                return ResourceManager.GetString("Something went wrong...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomyślnie stworzono katalog:.
        /// </summary>
        internal static string Successfully_created_directory_ {
            get {
                return ResourceManager.GetString("Successfully created directory:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomyślnie usunięto elementy.
        /// </summary>
        internal static string Successfully_deleted_elements {
            get {
                return ResourceManager.GetString("Successfully deleted elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomyślnie zmieniono nazwę do {0}.
        /// </summary>
        internal static string Successfully_renamed_to__0_ {
            get {
                return ResourceManager.GetString("Successfully renamed to {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zasób nie istnieje.
        /// </summary>
        internal static string The_resource_doesn_t_exist_on_the_filesystem {
            get {
                return ResourceManager.GetString("The resource doesn\'t exist on the filesystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folderu nie da się pobrać.
        /// </summary>
        internal static string This_is_a_folder__cannot_download_it_directly {
            get {
                return ResourceManager.GetString("This is a folder, cannot download it directly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wgrany/wgrane o sumarycznym rozmiarze.
        /// </summary>
        internal static string uploaded_of_summary_size {
            get {
                return ResourceManager.GetString("uploaded of summary size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie możesz używać znaków nie alfanumerycznych w nazwach katalogów.
        /// </summary>
        internal static string You_cannot_use_non_alphabetic_characters_in_directory_names {
            get {
                return ResourceManager.GetString("You cannot use non-alphabetic characters in directory names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje rządanie zostało zaakceptowane.
        /// </summary>
        internal static string Your_request_has_been_accepted {
            get {
                return ResourceManager.GetString("Your request has been accepted", resourceCulture);
            }
        }
    }
}
