//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PikaCore.Resources.Areas.Identity.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ManageController_pl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ManageController_pl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PikaCore.Resources.Areas.Identity.Controllers.ManageController.pl", typeof(ManageController_pl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zewnętrzne logowanie zostało dodane.
        /// </summary>
        internal static string The_external_login_was_added {
            get {
                return ResourceManager.GetString("The external login was added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zewnętrzne logowanie zostało usunięte.
        /// </summary>
        internal static string The_external_login_was_removed {
            get {
                return ResourceManager.GetString("The external login was removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje hasło zostało zmienione.
        /// </summary>
        internal static string Your_password_has_been_changed {
            get {
                return ResourceManager.GetString("Your password has been changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje hasło zostało ustawione.
        /// </summary>
        internal static string Your_password_has_been_set {
            get {
                return ResourceManager.GetString("Your password has been set", resourceCulture);
            }
        }
    }
}
