//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PikaCore.Resources.Areas.Identity.Models.AccountViewModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExternalLoginViewModel_pl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExternalLoginViewModel_pl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PikaCore.Resources.Areas.Identity.Models.AccountViewModels.ExternalLoginViewModel" +
                            ".pl", typeof(ExternalLoginViewModel_pl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres email jest wymagany dla autentykacji zewnętrznej.
        /// </summary>
        internal static string Email_address_is_required_for_external_authentication {
            get {
                return ResourceManager.GetString("Email address is required for external authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę, wprowadź poprawny adres email.
        /// </summary>
        internal static string Please__enter_a_valid_email_address {
            get {
                return ResourceManager.GetString("Please, enter a valid email address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę, podaj nazwę użytkownika.
        /// </summary>
        internal static string Please__provide_a_username {
            get {
                return ResourceManager.GetString("Please, provide a username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa użytkownika musi być dłuższa niż {2}, ale krótsza niż {1}.
        /// </summary>
        internal static string Username_must_be_at_least__2__and_not_longer_than__1_ {
            get {
                return ResourceManager.GetString("Username must be at least {2} and not longer than {1}", resourceCulture);
            }
        }
    }
}
