//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PikaCore.Resources.Areas.Identity.Models.AccountViewModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResetPasswordViewModel_pl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResetPasswordViewModel_pl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PikaCore.Resources.Areas.Identity.Models.AccountViewModels.ResetPasswordViewModel" +
                            ".pl", typeof(ResetPasswordViewModel_pl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdź aktualne hasło.
        /// </summary>
        internal static string Confirm_current_password {
            get {
                return ResourceManager.GetString("Confirm current password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualne hasło.
        /// </summary>
        internal static string Current_password {
            get {
                return ResourceManager.GetString("Current password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres email jest wymagany.
        /// </summary>
        internal static string Email_address_is_required {
            get {
                return ResourceManager.GetString("Email address is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę, wprowadź poprawny adres.
        /// </summary>
        internal static string Please__enter_a_valid_email_address {
            get {
                return ResourceManager.GetString("Please, enter a valid email address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musisz wprowadzić poprawne, aktualne hasło.
        /// </summary>
        internal static string You_have_to_enter_a_valid__current_password {
            get {
                return ResourceManager.GetString("You have to enter a valid, current password", resourceCulture);
            }
        }
    }
}
