//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PikaCore.Resources.Areas.Identity.Models.ManageViewModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IndexViewModel_pl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexViewModel_pl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PikaCore.Resources.Areas.Identity.Models.ManageViewModels.IndexViewModel.pl", typeof(IndexViewModel_pl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane konta.
        /// </summary>
        internal static string Account_Data {
            get {
                return ResourceManager.GetString("Account Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eksportuj.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z tego miejsca możesz zarządać eksportu swoich danych do pliku w formacie CSV, jak także możesz usunąć trwale swoje konto.
        /// </summary>
        internal static string From_here__you_can_request_export_of_your_data_to_CSV_file_or_just_delete_your_account {
            get {
                return ResourceManager.GetString("From here, you can request export of your data to CSV file or just delete your ac" +
                        "count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer telefonu.
        /// </summary>
        internal static string Phone_number {
            get {
                return ResourceManager.GetString("Phone number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta funkcjonalność nie jest teraz dostępna.
        /// </summary>
        internal static string This_feature_is_not_available_at_the_moment {
            get {
                return ResourceManager.GetString("This feature is not available at the moment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To pole jest wymagane.
        /// </summary>
        internal static string This_field_is_required {
            get {
                return ResourceManager.GetString("This field is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To nie jest poprawny numer telefonu.
        /// </summary>
        internal static string This_is_not_a_valid_phone_number {
            get {
                return ResourceManager.GetString("This is not a valid phone number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa użytkownika nie może być dłuższa niż {0}, ale i nie krótsza niż {1}.
        /// </summary>
        internal static string Username_cannot_be_longer_than__0___but_longer_than__1_ {
            get {
                return ResourceManager.GetString("Username cannot be longer than {0}, but longer than {1}", resourceCulture);
            }
        }
    }
}
