//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PikaCore.Resources.Areas.Core.Pages.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class About_pl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal About_pl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PikaCore.Resources.Areas.Core.Pages.Home.About.pl", typeof(About_pl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O systemie.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O systemie.
        /// </summary>
        internal static string About_System {
            get {
                return ResourceManager.GetString("About System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na ten moment, Pika Core używa mojego własnego rozwiązania do organizacji plików, który nazwałem VCOS - Virtual Categorized Object  System..
        /// </summary>
        internal static string As_for_now__Pika_Core_uses_custom_solution_for_organizing_files_which_I_called_VCOS___Virtual_Categorized_Object_System__ {
            get {
                return ResourceManager.GetString("As for now, Pika Core uses custom solution for organizing files which I called VC" +
                        "OS - Virtual Categorized Object System. ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klaster.
        /// </summary>
        internal static string Cluster {
            get {
                return ResourceManager.GetString("Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Głównym przeznaczeniem od samego początku  było i jest udsotępnianie zasobów, które gromadzę na swoim prywatnym serwerze..
        /// </summary>
        internal static string It_s_main_purpose_from_its_very_beginning_was_to_give_an_easy_access_to_all_resources_I_gather_on_my_server_s_filesystem__ {
            get {
                return ResourceManager.GetString("It\'s main purpose from its very beginning was to give an easy access to all resou" +
                        "rces I gather on my server\'s filesystem. ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pika Core jest pierwszą aplikacją typu Web, którą kiedykolwiek napisałem..
        /// </summary>
        internal static string Pika_Core_is_a_first_web_app_I_ve_ever_build_ {
            get {
                return ResourceManager.GetString("Pika Core is a first web app I\'ve ever build.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pika Core jest częścią.
        /// </summary>
        internal static string Pika_Core_is_a_subsystem_of {
            get {
                return ResourceManager.GetString("Pika Core is a subsystem of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To jest PikaCore aka Hannah.
        /// </summary>
        internal static string This_is_PikaCore_aka_Hannah {
            get {
                return ResourceManager.GetString("This is PikaCore aka Hannah", resourceCulture);
            }
        }
    }
}
